image_config: &image_config
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.8.0

ignore_ghpages: &ignore_ghpages
  filters:
    branches:
      ignore:
        - gh-page

restore_cache_config: &restore_cache_config
  name: Restore Yarn Package Cache
  keys:
    - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
    - yarn-packages-{{ .Branch }}
    - yarn-packages-master
    - yarn-packages-

save_cache_config: &save_cache_config
  name: Save Yarn Package Cache
  key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
  paths:
    - node_modules/

version: 2
jobs:
  build:
    <<: *image_config
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_config
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          <<: *save_cache_config
      - run:
          name: build
          command: yarn build
  test:
    <<: *image_config
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_config
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          <<: *save_cache_config
      - run:
          name: test
          command: yarn test:prod
  deploy_docs:
    <<: *image_config
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_config
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          <<: *save_cache_config
      - run:
          name: deploy_docs
          command: yarn deploy-docs
workflows:
  version: 2
  build_test_and_deploy_docs:
    jobs:
      - build:
          <<: *ignore_ghpages
      - test:
          <<: *ignore_ghpages
      - deploy_docs: 
          requires:
            - build
            - test
          <<: *ignore_ghpages
